---
layout: model
title: Mensaje de Whatsapp
parent: Inicio
nav_order: 0
---

¡Buenos días! Mi nombre es Nahuel Ourthe y soy el tutor del curso *"CC"* de *_Aprender En Red_* al cual se inscribió; los voy a estar acompañando durante todo el cursado para guiarlos.
Le escribía para comentarle que *hoy* comenzó la semana de inducción del curso.
Al correo electrónico que usó para registrarse le enviamos el *usuario*, *contraseña* y las instrucciones para acceder al aula.
El link para ingresar al aula virtual es el siguiente: 
https://www.edu.campusaprenderenred.com 
Si no lo recibió por favor revise en la carpeta de *correo no deseado* o "*spam*".
Si tampoco está ahí, escríbame así lo solucionamos.
Esta semana del curso es de _inducción_. El lunes que viene empieza el Módulo 1 del curso: M1. 
Si tiene algún inconveniente para ingresar al aula puede escribirme por este medio, una vez que haya ingresado al aula la comunicación es por allí. *¡¡Le damos la bienvenida!!*
